### ISSUE TITLE
http://rakyll.pizza is serving "cannot render this page"

### ISSUE THREAD

**Issue by dmitshur** [rakyll/pizza#2]
This is causing the vanity Go import paths not to work:

```
$ curl -i 'http://rakyll.pizza/'
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
X-Cloud-Trace-Context: 254c6bd1bf8ffbf81e5e19b8b8cfc34a;o=1
Date: Wed, 09 Aug 2017 21:29:19 GMT
Server: Google Frontend
Content-Length: 154

<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta name="go-import" content="cannot render the page

$ curl -i 'http://rakyll.pizza/cheese'
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
X-Cloud-Trace-Context: 7aee94f5824e8a4389da9cac7f1bc538;o=1
Date: Wed, 09 Aug 2017 21:36:43 GMT
Server: Google Frontend
Content-Length: 19

404 page not found
```

/cc @rakyll FYI.

P.S. Jaana, you're [not watching](https://github.com/rakyll/pizza/watchers) your own repository, so you're not going to get notified of issues reported or [PRs sent](https://github.com/rakyll/pizza/pulls) unless they explicitly @-mention you. Is that intentional?

**Comment by rakyll** [comment]
GitHub might have not signed me up automatically :(

I am looking at the issue as soon as I find some time.

**Comment by dmitshur** [comment]
> GitHub might have not signed me up automatically :(

Yeah, I think it has an option to do it, but that option can be turned off.

![image](https://user-images.githubusercontent.com/1924134/29145070-7284b050-7d29-11e7-9952-1ece4c728f7f.png)

> I am looking at the issue as soon as I find some time.

Awesome, thank you! I am looking forward to having the 🍕 with 🧀 restored to full functionality. :)

**Comment by rakyll** [comment]
@shurcooL, fixed my setting now, thanks!!

rakyll.pizza is back. I never thought 🍕, 🧀, and 🍍 uptime is so crucial :) Here, go get some: https://godoc.org/rakyll.pizza.

**Comment by dmitshur** [comment]
Thank you very much!

Primarily, I wanted to test that https://gotools.org/rakyll.pizza works okay. It does now. 👍
